"""Build and validate Phase 3 metric-contract artifacts without calculating KPIs."""

from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "reports" / "metric-contract"
RAW = ROOT / "data" / "raw"
ALL_STATUSES = ["created", "approved", "invoiced", "processing", "shipped", "delivered", "canceled", "unavailable"]
COMMERCIAL = ["approved", "invoiced", "processing", "shipped", "delivered"]

METRICS = [
 {"metric_id":"MET-001","metric_name":"Total Orders","final_status":"APPROVED","business_definition":"Distinct source orders placed during the reporting period, regardless of lifecycle status.","grain":"order","population_rule":"All observed statuses; valid non-null order_id and purchase timestamp.","date_rule":"order_purchase_timestamp; no fallback","key_identifier":"order_id","numerator_rule":"COUNT(DISTINCT order_id)","denominator_rule":"Not applicable","null_rule":"Null order ID/date is ineligible and must fail DQ; none observed.","zero_rule":"Not applicable","DQ_dependencies":"DQ-001; DQ-003; DQ-005; DQ-008; DQ-016","reconciliation_rule":"Distinct order_id from orders under identical date/status filter; exact equality.","limitations":"A source order is counted even if later canceled/unavailable or lacks child records.","rationale":"Preserves the literal meaning of Total Orders and separates delivered volume into MET-002.","unresolved_condition":"None","future_model_requirement":"MODEL-001; PENDING_PHASE_4 implementation"},
 {"metric_id":"MET-002","metric_name":"Delivered Status Orders","final_status":"APPROVED","business_definition":"Distinct orders whose source lifecycle status is delivered.","grain":"order","population_rule":"Include delivered only; do not require customer-delivery timestamp.","date_rule":"order_purchase_timestamp; no fallback","key_identifier":"order_id","numerator_rule":"COUNT(DISTINCT order_id WHERE order_status='delivered')","denominator_rule":"Not applicable","null_rule":"Status/order/date required; actual-delivery timestamp is not required for this status metric.","zero_rule":"Not applicable","DQ_dependencies":"DQ-003; DQ-008; DQ-009","reconciliation_rule":"Distinct delivered order_id in orders; exact equality.","limitations":"Measures source status, not timestamp-complete deliveries; eight delivered-status orders lack actual-delivery timestamps.","rationale":"Keeps status semantics distinct from MET-008/009 endpoint-complete populations.","unresolved_condition":"None","future_model_requirement":"MODEL-001"},
 {"metric_id":"MET-003","metric_name":"Product GMV","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Sum of item selling prices for lifecycle-active commercial orders; freight excluded.","grain":"order item","population_rule":"Include approved, invoiced, processing, shipped, delivered orders with item rows; exclude created, canceled, unavailable.","date_rule":"parent order_purchase_timestamp; no fallback","key_identifier":"order_id + order_item_id","numerator_rule":"SUM(order_items.price)","denominator_rule":"Not applicable","null_rule":"Price/key/purchase date required; no imputation.","zero_rule":"Zero price would be included and warned; none observed.","DQ_dependencies":"DQ-007; DQ-008; DQ-012; DQ-015; DQ-016","reconciliation_rule":"Eligible source item price sum at validated item key; exact equality within 0.01 currency-unit tolerance.","limitations":"Not revenue, recognized revenue, net sales, cash received, or profit; refunds/returns/costs are unavailable.","rationale":"Uses the contractually intended price-only measure and prevents payment/freight substitution.","unresolved_condition":"Refund/return semantics unavailable","future_model_requirement":"MODEL-002; independent item fact"},
 {"metric_id":"MET-004","metric_name":"Gross Order Value","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Sum of item selling price plus item freight value for lifecycle-active commercial orders.","grain":"order item","population_rule":"Same as MET-003.","date_rule":"parent order_purchase_timestamp; no fallback","key_identifier":"order_id + order_item_id","numerator_rule":"SUM(price + freight_value)","denominator_rule":"Not applicable","null_rule":"Both components and keys required; no imputation.","zero_rule":"Zero freight is valid and included; zero price would be included and warned.","DQ_dependencies":"DQ-007; DQ-008; DQ-015; DQ-016","reconciliation_rule":"Independent eligible item-grain sum; exact equality within 0.01.","limitations":"Not payment value, revenue, net sales, or profit.","rationale":"Separates freight-inclusive value from Product GMV.","unresolved_condition":"Refund/return semantics unavailable","future_model_requirement":"MODEL-002"},
 {"metric_id":"MET-005","metric_name":"Average Order Value (Product GMV)","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Average order-level Product GMV among lifecycle-active commercial orders represented by at least one eligible item.","grain":"items pre-aggregated to order, then reporting group","population_rule":"Same statuses as MET-003; denominator includes only eligible orders with at least one eligible item.","date_rule":"order_purchase_timestamp; no fallback","key_identifier":"order_id","numerator_rule":"SUM(order-level Product GMV)","denominator_rule":"COUNT(DISTINCT eligible order_id with >=1 eligible item)","null_rule":"Orders without items excluded from this metric only and coverage disclosed.","zero_rule":"Zero order Product GMV would be included if source-valid.","DQ_dependencies":"DQ-007; DQ-008; DQ-015; DQ-016","reconciliation_rule":"Numerator reconciles to MET-003 source control; denominator to distinct eligible item-bearing orders; tolerance 0.01.","limitations":"Freight excluded; not average payment or revenue per order.","rationale":"Avoids denominator bias from itemless orders and fanout.","unresolved_condition":"Refund/return semantics unavailable","future_model_requirement":"MODEL-001 + MODEL-002 with item-to-order pre-aggregation"},
 {"metric_id":"MET-006","metric_name":"Unique Customers","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Distinct stable customers associated with at least one lifecycle-active commercial order in the reporting period.","grain":"stable customer","population_rule":"Approved, invoiced, processing, shipped, delivered orders; valid customer mapping.","date_rule":"order_purchase_timestamp; no fallback","key_identifier":"customer_unique_id","numerator_rule":"COUNT(DISTINCT customer_unique_id)","denominator_rule":"Not applicable","null_rule":"Stable ID/order/date required; no imputation.","zero_rule":"Not applicable","DQ_dependencies":"DQ-005; DQ-008; DQ-011; DQ-016; DQ-018","reconciliation_rule":"Independent distinct customer_unique_id after eligible order-to-customer join; exact equality.","limitations":"Observed dataset customers, not all historical/lifetime customers; period/window censoring applies.","rationale":"Uses validated stable identity rather than order-associated customer_id.","unresolved_condition":"Observation boundaries may be incomplete","future_model_requirement":"MODEL-001 + MODEL-005"},
 {"metric_id":"MET-007","metric_name":"Observed Repeat Customer Rate","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Share of stable customers with at least two eligible orders within the same declared observation window among customers with at least one eligible order.","grain":"stable customer over fixed window","population_rule":"Approved, invoiced, processing, shipped, delivered orders within one explicitly declared window.","date_rule":"order_purchase_timestamp; no fallback","key_identifier":"customer_unique_id + distinct order_id","numerator_rule":"COUNT(DISTINCT customer_unique_id HAVING COUNT(DISTINCT eligible order_id)>=2)","denominator_rule":"COUNT(DISTINCT customer_unique_id HAVING COUNT(DISTINCT eligible order_id)>=1)","null_rule":"Stable ID/order/date required; no imputation.","zero_rule":"Return null/NA rather than divide by zero if denominator is zero.","DQ_dependencies":"DQ-008; DQ-011; DQ-016; DQ-018","reconciliation_rule":"Rebuild customer-level eligible distinct-order counts from source; numerator <= denominator; exact counts.","limitations":"Not retention or lifetime behavior; customers have unequal exposure near window boundaries.","rationale":"A defensible observed repeat measure is calculable if censoring is explicit.","unresolved_condition":"No supported exposure adjustment; interpret descriptively","future_model_requirement":"MODEL-001 + MODEL-005; window parameter"},
 {"metric_id":"MET-008","metric_name":"Average Delivery Lead Time","final_status":"APPROVED","business_definition":"Mean elapsed days from purchase timestamp to actual customer delivery for endpoint-complete delivered orders.","grain":"order","population_rule":"Status delivered; purchase and customer-delivery timestamps non-null; delivery >= purchase.","date_rule":"purchase-cohort attribution using order_purchase_timestamp; no fallback","key_identifier":"order_id","numerator_rule":"SUM(delivered_customer_timestamp - purchase_timestamp in fractional days)","denominator_rule":"COUNT(eligible delivered orders)","null_rule":"Missing endpoints excluded from this metric only; count disclosed; no imputation.","zero_rule":"Zero-day duration is valid; negative duration is ineligible and warned.","DQ_dependencies":"DQ-005; DQ-006; DQ-008; DQ-009; DQ-016","reconciliation_rule":"Eligible order count and total duration independently recomputed from orders; exact count and numeric tolerance 1e-9 days before display rounding.","limitations":"Mean is sensitive to distribution tails; median may be shown only as diagnostic. Timezone-naive timestamps.","rationale":"Uses semantically direct customer delivery endpoints; approval/carrier reversals do not affect formula.","unresolved_condition":"None for current endpoints","future_model_requirement":"MODEL-001 with endpoint eligibility flag"},
 {"metric_id":"MET-009","metric_name":"Late Delivery Rate","final_status":"APPROVED","business_definition":"Share of endpoint-complete delivered orders whose actual customer-delivery timestamp is later than the estimated-delivery timestamp.","grain":"order","population_rule":"Status delivered; valid purchase, actual-delivery, and estimated-delivery timestamps; actual >= purchase.","date_rule":"purchase-cohort attribution using order_purchase_timestamp; no fallback","key_identifier":"order_id","numerator_rule":"COUNT(eligible order_id WHERE actual_delivery > estimated_delivery)","denominator_rule":"COUNT(eligible delivered order_id with both endpoints)","null_rule":"Missing actual/estimate excluded from this metric only and disclosed.","zero_rule":"Zero numerator displays 0%; zero denominator returns null/NA.","DQ_dependencies":"DQ-005; DQ-006; DQ-008; DQ-009; DQ-016","reconciliation_rule":"Numerator/denominator independently counted from eligible orders; 0 <= numerator <= denominator; exact equality.","limitations":"Equality is on-time; measures source estimate adherence, not causality or service quality in isolation.","rationale":"Late delivery is a business outcome, not a DQ defect; eight missing actual timestamps are excluded.","unresolved_condition":"None","future_model_requirement":"MODEL-001 with shared MET-009/015 eligibility flag"},
 {"metric_id":"MET-010","metric_name":"Average Review Score","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Unweighted mean of order-level mean review scores, giving each reviewed order equal portfolio weight.","grain":"review events aggregated to order, then reporting group","population_rule":"All order statuses with >=1 matched review row and valid score 1–5.","date_rule":"parent order_purchase_timestamp; no fallback; review-date view is secondary only","key_identifier":"order_id; preserve all source review rows within order","numerator_rule":"SUM(order-level mean(review_score))","denominator_rule":"COUNT(DISTINCT reviewed order_id)","null_rule":"Invalid/null scores excluded and disclosed; none observed. Orders without reviews excluded and coverage disclosed.","zero_rule":"Not applicable; valid domain 1–5.","DQ_dependencies":"DQ-002; DQ-008; DQ-010; DQ-016","reconciliation_rule":"Recompute per-order means from all source rows, then verify one aggregate row per order and exact reviewed-order denominator.","limitations":"Order-level mean is an analytical construction; repeated relationship semantics/revision history are unavailable.","rationale":"Equal order weighting avoids overweighting orders with multiple review rows without unsupported single-record selection.","unresolved_condition":"No authoritative canonical source review exists","future_model_requirement":"MODEL-004 order-review aggregate preserving event counts"},
 {"metric_id":"MET-011","metric_name":"Item Volume","final_status":"APPROVED","business_definition":"Count of validated order-item lines for lifecycle-active commercial orders.","grain":"order item","population_rule":"Approved, invoiced, processing, shipped, delivered orders with valid item key.","date_rule":"parent order_purchase_timestamp; no fallback","key_identifier":"order_id + order_item_id","numerator_rule":"COUNT(valid item key)","denominator_rule":"Not applicable","null_rule":"Invalid/null item key excluded only after DQ failure; none observed.","zero_rule":"Not applicable","DQ_dependencies":"DQ-002; DQ-003; DQ-008; DQ-016","reconciliation_rule":"Eligible source item-key count; exact equality.","limitations":"Item lines are not necessarily physical unit quantity beyond source sequence semantics.","rationale":"Preserves native validated item grain.","unresolved_condition":"None","future_model_requirement":"MODEL-002"},
 {"metric_id":"MET-012","metric_name":"Freight Value","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Sum of recorded item-level freight value for lifecycle-active commercial orders.","grain":"order item","population_rule":"Same statuses and item population as MET-003.","date_rule":"parent order_purchase_timestamp; no fallback","key_identifier":"order_id + order_item_id","numerator_rule":"SUM(freight_value)","denominator_rule":"Not applicable","null_rule":"Null/non-parsing freight is ineligible and warned; none observed.","zero_rule":"Zero freight is valid and included; 383 source rows observed.","DQ_dependencies":"DQ-007; DQ-008; DQ-015; DQ-016","reconciliation_rule":"Independent eligible item-grain freight sum; exact equality within 0.01.","limitations":"Recorded freight value is not validated carrier cost or profit impact.","rationale":"Preserves source zeros and item grain.","unresolved_condition":"Economic cost semantics unavailable","future_model_requirement":"MODEL-002"},
 {"metric_id":"MET-013","metric_name":"Freight Burden","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Recorded freight value as a share of gross order value for the same eligible item population.","grain":"order item aggregated to reporting group","population_rule":"Same as MET-003; aggregate components before division.","date_rule":"parent order_purchase_timestamp; no fallback","key_identifier":"order_id + order_item_id","numerator_rule":"SUM(freight_value)","denominator_rule":"SUM(price + freight_value)","null_rule":"Valid components required; no imputation.","zero_rule":"Zero freight included; zero denominator returns null/NA and warning.","DQ_dependencies":"DQ-007; DQ-008; DQ-015; DQ-016","reconciliation_rule":"Components reconcile independently to MET-012 and MET-004 controls; ratio recomputed after aggregation.","limitations":"Weighted ratio, not mean row ratio; freight value is not carrier cost.","rationale":"Avoids mathematically biased average-of-ratios calculation.","unresolved_condition":"Economic cost semantics unavailable","future_model_requirement":"MODEL-002"},
 {"metric_id":"MET-014","metric_name":"Recorded Payment Value","final_status":"APPROVED_WITH_LIMITATION","business_definition":"Sum of recorded payment-sequence values for orders in the reporting period, independently of item values.","grain":"payment sequence","population_rule":"All statuses with valid payment rows; missing-payment orders absent and coverage disclosed.","date_rule":"parent order_purchase_timestamp; no fallback","key_identifier":"order_id + payment_sequential","numerator_rule":"SUM(payment_value)","denominator_rule":"Not applicable","null_rule":"Valid payment key/value/date required; no imputation.","zero_rule":"Zero payment values are valid source records, included, and warned; nine observed.","DQ_dependencies":"DQ-007; DQ-008; DQ-015; DQ-016","reconciliation_rule":"Independent payment-grain sum under identical order/date filter; exact equality within 0.01; never reconcile through item join.","limitations":"Not Product GMV, cash settlement, recognized revenue, or net of refunds/chargebacks; payment lifecycle metadata is absent.","rationale":"Controlled rename makes source semantics explicit and prevents interchange with price.","unresolved_condition":"Settlement/refund semantics unavailable","future_model_requirement":"MODEL-003 independent payment fact/aggregate"},
 {"metric_id":"MET-015","metric_name":"On-time Delivery Rate","final_status":"APPROVED","business_definition":"Share of the MET-009 eligible delivered-order population delivered on or before the estimated timestamp.","grain":"order","population_rule":"Exactly the same denominator population as MET-009.","date_rule":"purchase-cohort attribution using order_purchase_timestamp; no fallback","key_identifier":"order_id","numerator_rule":"COUNT(eligible order_id WHERE actual_delivery <= estimated_delivery)","denominator_rule":"Same eligible denominator as MET-009","null_rule":"Same as MET-009.","zero_rule":"Zero numerator displays 0%; zero denominator returns null/NA.","DQ_dependencies":"DQ-005; DQ-006; DQ-008; DQ-009; DQ-016","reconciliation_rule":"MET-015 numerator + MET-009 numerator = shared denominator; rates sum to 100% before rounding.","limitations":"Complement of MET-009 only under identical population; not a causal service-quality measure.","rationale":"Enforces denominator consistency and equality-as-on-time semantics.","unresolved_condition":"None","future_model_requirement":"MODEL-001 shared eligibility flag"},
]

SOURCE_COLUMNS = {
 "MET-001":{"orders":{"order_id","order_status","order_purchase_timestamp"}},
 "MET-002":{"orders":{"order_id","order_status","order_purchase_timestamp"}},
 "MET-003":{"orders":{"order_id","order_status","order_purchase_timestamp"},"order_items":{"order_id","order_item_id","price"}},
 "MET-004":{"orders":{"order_id","order_status","order_purchase_timestamp"},"order_items":{"order_id","order_item_id","price","freight_value"}},
 "MET-005":{"orders":{"order_id","order_status","order_purchase_timestamp"},"order_items":{"order_id","order_item_id","price"}},
 "MET-006":{"orders":{"order_id","customer_id","order_status","order_purchase_timestamp"},"customers":{"customer_id","customer_unique_id"}},
 "MET-007":{"orders":{"order_id","customer_id","order_status","order_purchase_timestamp"},"customers":{"customer_id","customer_unique_id"}},
 "MET-008":{"orders":{"order_id","order_status","order_purchase_timestamp","order_delivered_customer_date"}},
 "MET-009":{"orders":{"order_id","order_status","order_purchase_timestamp","order_delivered_customer_date","order_estimated_delivery_date"}},
 "MET-010":{"orders":{"order_id","order_status","order_purchase_timestamp"},"reviews":{"order_id","review_id","review_score"}},
 "MET-011":{"orders":{"order_id","order_status","order_purchase_timestamp"},"order_items":{"order_id","order_item_id"}},
 "MET-012":{"orders":{"order_id","order_status","order_purchase_timestamp"},"order_items":{"order_id","order_item_id","freight_value"}},
 "MET-013":{"orders":{"order_id","order_status","order_purchase_timestamp"},"order_items":{"order_id","order_item_id","price","freight_value"}},
 "MET-014":{"orders":{"order_id","order_status","order_purchase_timestamp"},"payments":{"order_id","payment_sequential","payment_value"}},
 "MET-015":{"orders":{"order_id","order_status","order_purchase_timestamp","order_delivered_customer_date","order_estimated_delivery_date"}},
}
FILES={"orders":"olist_orders_dataset.csv","order_items":"olist_order_items_dataset.csv","customers":"olist_customers_dataset.csv","reviews":"olist_order_reviews_dataset.csv","payments":"olist_order_payments_dataset.csv"}

def statuses(metric_id):
    if metric_id=="MET-001": return ALL_STATUSES
    if metric_id in {"MET-002","MET-008","MET-009","MET-015"}: return ["delivered"]
    if metric_id in {"MET-003","MET-004","MET-005","MET-006","MET-007","MET-011","MET-012","MET-013"}: return COMMERCIAL
    return ALL_STATUSES

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    display_name_refinements = {
        "MET-006": "Observed Unique Customers",
        "MET-010": "Average Order-Level Review Score",
        "MET-014": "Recorded Payment Value",
    }
    for metric in METRICS:
        metric["metric_name"] = display_name_refinements.get(metric["metric_id"], metric["metric_name"])
        if metric["metric_id"] == "MET-014":
            metric["limitations"] = ("Not Product GMV, revenue, recognized revenue, cash received, net sales, "
                                     "or net of refunds/chargebacks; payment lifecycle metadata is absent.")
        if metric["unresolved_condition"] == "None":
            metric["unresolved_condition"] = "NOT_APPLICABLE"
    pd.DataFrame(METRICS).to_csv(OUT/"metric-decision-register.csv",index=False)
    status_rows=[]
    for m in METRICS:
        inc=set(statuses(m["metric_id"]))
        for s in ALL_STATUSES:
            status_rows.append({"metric_id":m["metric_id"],"order_status":s,"decision":"INCLUDE" if s in inc else "EXCLUDE",
                "rationale":m["population_rule"],"required_fields":"See metric decision register","caveat":"Metric-specific rule; never reuse as global filter"})
    pd.DataFrame(status_rows).to_csv(OUT/"status-population-matrix.csv",index=False)
    pd.DataFrame([{"metric_id":m["metric_id"],"primary_reporting_date":m["date_rule"].split(';')[0],"reason":"Consistent purchase-cohort attribution for source orders and derived events","fallback_allowed":"NO","fallback_policy":"None","missing_date_treatment":"Metric-ineligible and coverage warning","temporal_DQ_dependencies":"DQ-005; DQ-006; DQ-009 as applicable"} for m in METRICS]).to_csv(OUT/"date-attribution-matrix.csv",index=False)
    calc={"MET-001":"order","MET-002":"order","MET-003":"order item","MET-004":"order item","MET-005":"order after item aggregation","MET-006":"stable customer","MET-007":"stable customer over window","MET-008":"order","MET-009":"order","MET-010":"order after review-event aggregation","MET-011":"order item","MET-012":"order item","MET-013":"reporting group after item aggregation","MET-014":"payment sequence","MET-015":"order"}
    pd.DataFrame([{"metric_id":m["metric_id"],"source_grain":m["grain"],"calculation_grain":calc[m["metric_id"]],"reporting_grain":"selected reporting dimension/time period","required_pre_aggregation":"Yes" if m["metric_id"] in {"MET-005","MET-007","MET-010","MET-013"} else "No beyond reporting aggregation","fanout_risk":"CRITICAL item/payment" if m["metric_id"] in {"MET-003","MET-004","MET-005","MET-012","MET-013","MET-014"} else "Controlled","safe_join_requirements":m["future_model_requirement"]} for m in METRICS]).to_csv(OUT/"metric-grain-matrix.csv",index=False)
    br={"MET-001":"BR-001","MET-002":"BR-001; BR-017","MET-003":"BR-002; BR-009","MET-004":"BR-002","MET-005":"BR-002; BR-009","MET-006":"BR-005","MET-007":"BR-006; BR-007","MET-008":"BR-015; BR-017","MET-009":"BR-015; BR-017","MET-010":"BR-018; BR-020","MET-011":"BR-009","MET-012":"BR-010; BR-016","MET-013":"BR-010","MET-014":"BR-021; BR-022","MET-015":"BR-015; BR-017"}
    an={"MET-001":"AN-001; AN-002","MET-002":"AN-001","MET-003":"AN-001; AN-002; AN-006; AN-007","MET-004":"AN-001","MET-005":"AN-001; AN-002; AN-006","MET-006":"AN-002; AN-003","MET-007":"AN-003; AN-004","MET-008":"AN-007; AN-008","MET-009":"AN-008; AN-010","MET-010":"AN-007; AN-009; AN-010","MET-011":"AN-006","MET-012":"AN-006; AN-008","MET-013":"AN-006","MET-014":"AN-011","MET-015":"AN-008"}
    pd.DataFrame([{"metric_id":m["metric_id"],"business_requirements":br[m["metric_id"]],"data_requirements":"DATA-001–DATA-008","DQ_requirements":m["DQ_dependencies"],"future_model_ids":m["future_model_requirement"],"future_analysis_ids":an[m["metric_id"]],"acceptance_criteria":"AC-004; AC-005; AC-007; AC-010; AC-013; AC-016; AC-017–AC-024"} for m in METRICS]).to_csv(OUT/"traceability-matrix.csv",index=False)

    tests=[]
    def add(mid,name,result,evidence,expected_status="PASS"):
        tests.append({"test_id":f"MCT-{len(tests)+1:03d}","metric_id":mid,"test_name":name,
                      "result":result,"expected_status":expected_status,"evidence":evidence})
    schemas={t:set(pd.read_csv(RAW/f, nrows=0).columns) for t,f in FILES.items()}
    for m in METRICS:
        mid=m["metric_id"]
        missing=[]
        for table,cols in SOURCE_COLUMNS[mid].items(): missing += [f"{table}.{c}" for c in cols-schemas[table]]
        add(mid,"Required source columns exist","PASS" if not missing else "BLOCKED",str(missing or "all present"))
        add(mid,"Final status assigned","PASS" if m["final_status"] in {"APPROVED","APPROVED_WITH_LIMITATION","BLOCKED"} else "BLOCKED",m["final_status"])
        add(mid,"Population/date/grain/reconciliation defined","PASS" if all(m[k] for k in ["population_rule","date_rule","grain","reconciliation_rule"]) else "BLOCKED","contract fields populated")
    add("MET-003","Product GMV excludes freight and payment","PASS",METRICS[2]["numerator_rule"])
    add("MET-006","Stable customer identity used","PASS",METRICS[5]["key_identifier"])
    add("MET-007","Repeat metric is observational","PASS",METRICS[6]["metric_name"])
    add("MET-009","Late-delivery denominator explicit","PASS",METRICS[8]["denominator_rule"])
    add("MET-010","Review policy uses order-level mean","WARN",METRICS[9]["limitations"],expected_status="WARN")
    add("MET-014","Payment fact independent of item fact","PASS",METRICS[13]["reconciliation_rule"])
    forbidden=[x for x in [m["metric_name"].lower() for m in METRICS] if any(w in x for w in ["profit","net revenue","net sales","lifetime value","retention rate"])]
    add("ALL","Forbidden overclaiming terminology absent","PASS" if not forbidden else "BLOCKED",str(forbidden or "none"))
    pd.DataFrame(tests).to_csv(OUT/"metric-contract-test-results.csv",index=False)
    if any(t["result"]=="BLOCKED" for t in tests): sys.exit(1)
    print(pd.Series([m["final_status"] for m in METRICS]).value_counts().to_dict())
    print(pd.Series([t["result"] for t in tests]).value_counts().to_dict())

if __name__=="__main__": main()
